[package]
name = "tlap"
description = "Transliterate Language for an Accessibility Purpose"
version = "0.3.2"
authors = ["Bricky <bricky149@teknik.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deepspeech = "0.9.*"
audrey = "*"
dasp_interpolate = { version = "*", features = ["linear"] }
dasp_signal = "*"
hound = "*"
portaudio = "*"

[profile.release]
codegen-units = 4
lto = true
panic = "abort"
